In [9]:
import pandas as pd
import pathlib

In [11]:
# Load all data tables
df_cashflow = pd.read_csv("../data/clean/cashflow_statement/cashflow_statement.csv")
df_balance = pd.read_csv("../data/clean/balance_sheet_statement/balance_sheet_statement.csv")
df_charts = pd.read_csv("../data/clean/charts/charts.csv")
df_profile = pd.read_csv("../data/clean/company_profile/company_profile.csv")
df_income = pd.read_csv("../data/clean/income_statement/income_statement.csv")

In [13]:
#### Create symbols table, remove dynamic data (things we expect to change regularly)
rm_cols = [
    "price",
    "beta",
    "vol_avg",
    "mkt_cap",
    "last_div",
    "range",
    "changes",
    "full_time_employees",
    "zip",
    "dcf_diff",
    "dcf",
    "image",
    "default_image"
]

# Drop unneeded columns, save
df_profile.drop(rm_cols, axis=1, inplace=True)

# Save to folder
path = pathlib.Path("../data/db_tables/profile/")
if not path.exists: path.mkdir(parents=True, exists_ok=True)
    
df_profile.to_csv(path.joinpath("profile.csv"), index=False)
df_profile.head()

,symbol,company_name,currency,cik,isin,cusip,exchange,exchange_short_name,industry,website,...,country,phone,address,city,state,ipo_date,is_etf,is_actively_trading,is_adr,is_fund
0,TSLA,"Tesla, Inc.",USD,1318605,US88160R1014,88160R101,NASDAQ Global Select,NASDAQ,Auto - Manufacturers,https://www.tesla.com,...,US,512 516 8177,1 Tesla Road,Austin,TX,2010-06-29,False,True,False,False
1,GOOGL,Alphabet Inc.,USD,1652044,US02079K3059,02079K305,NASDAQ Global Select,NASDAQ,Internet Content & Information,https://www.abc.xyz,...,US,650 253 0000,1600 Amphitheatre Parkway,Mountain View,CA,2004-08-19,False,True,False,False
2,OSCR,"Oscar Health, Inc.",USD,1568651,US6877931096,687793109,New York Stock Exchange,NYSE,Healthcare - Plans,https://www.hioscar.com,...,US,(646) 403-3677,75 Varick Street,New York,NY,2021-03-03,False,True,False,False
3,MSFT,Microsoft Corporation,USD,789019,US5949181045,594918104,NASDAQ Global Select,NASDAQ,Software - Infrastructure,https://www.microsoft.com,...,US,425 882 8080,One Microsoft Way,Redmond,WA,1986-03-13,False,True,False,False
4,SPY,SPDR S&P 500 ETF Trust,USD,884394,US78462F1030,78462F103,New York Stock Exchange Arca,AMEX,NaN,http://www.spdrs.com,...,US,NaN,NaN,New York,NaN,1993-01-29,True,True,False,False

In [14]:
df_profile.columns

Index(['symbol', 'company_name', 'currency', 'cik', 'isin', 'cusip',
       'exchange', 'exchange_short_name', 'industry', 'website', 'description',
       'ceo', 'sector', 'country', 'phone', 'address', 'city', 'state',
       'ipo_date', 'is_etf', 'is_actively_trading', 'is_adr', 'is_fund'],
      dtype='object')

In [ ]:
#### Create charts table